/*
 * This file was generated by the Gradle "init" task.
 */

rootProject.name = "BlockHighlightBoundaries"
include(":BlockHighlightBoundaries-core")
include(":BlockHighlightBoundaries-packetevents1")
include(":BlockHighlightBoundaries-packetevents2")
include(":BlockHighlightBoundaries-protocollib")
include(":BlockHighlightBoundaries-plugin")

project(":BlockHighlightBoundaries-core").projectDir = file("core")
project(":BlockHighlightBoundaries-packetevents1").projectDir = file("impl/packetevents1")
project(":BlockHighlightBoundaries-packetevents2").projectDir = file("impl/packetevents2")
project(":BlockHighlightBoundaries-protocollib").projectDir = file("impl/protocollib")
project(":BlockHighlightBoundaries-plugin").projectDir = file("plugin")
