[versions]
pluginYml = "0.8.0"
paper = "1.21.11-R0.1-SNAPSHOT"
paperweightUserdev = "2.0.0-beta.19"
griefPrevention = "17.0.0"
netty = "4.2.6.Final"
planarWrappers = "4.0.0"
protocolLib = "5.3.0"
packetEvents2 = "2.4.0"
floodgate = "2.2.0-SNAPSHOT"
messagesHelper = "1.1-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
paperweightBundle = { group = "io.papermc.paper", name = "dev-bundle", version.ref = "paper" }
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref  = "griefPrevention" }
netty =  { group = "io.netty", name = "netty-all", version.ref  = "netty" }
planarWrappers =  { group = "com.github.jikoo", name = "planarwrappers", version.ref  = "planarWrappers" }
protocolLib = { group = "com.github.dmulloy2", name = "ProtocolLib", version.ref = "protocolLib"}
packetEvents2 = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetEvents2" }
floodgate = { group = "org.geysermc.floodgate", name = "api", version.ref = "floodgate" }
messagesHelper = { group = "uk.co.notnull", name= "MessagesHelper-paper", version.ref = "messagesHelper" }

[plugins]
pluginYml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYml" }
paperweightUserdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweightUserdev" }
